version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - PIP_ROOT_USER_ACTION=ignore

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5000:80'

      - '25:25'

      - '143:143'
    volumes:

      - smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data: