version: '3.8'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - PIP_ROOT_USER_ACTION=ignore
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core worker --loglevel INFO
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5000:80'

      - '25:25'

      - '143:143'
    volumes:

      - smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data: